# .github/workflows/groq-inference.yml

name: Run Groq Script (on inference_groq_2.py changes)

on:
  push:
    branches:
      - main
    paths:
      - inference_groq_2.py  # Trigger only if this notebook is changed

  workflow_dispatch:  # Optional: allow manual run from GitHub UI

jobs:
  run-groq:
    runs-on: ubuntu-latest

    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install groq

      - name: Run converted script
        run: python inference_groq_2.py
